
volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    restart: always
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: bobrovskii/taski_backend
    restart: always
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: bobrovskii/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: bobrovskii/taski_gateway
    restart: always
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80